color_range:
  low:
    red: 60
    green: 100
    blue: 0
  high:
    red: 255
    green: 255
    blue: 95
  hsv_low:
    - 29
    - 90
    - 90
  hsv_high:
    - 64
    - 255
    - 255
detect_zone:
  down_right:
    x: 1000
    y: 700
  top_left:
    x: 300
    y: 360
limit_pixel:
  x: 30
  y: 30
min_contour_area: 50
robot_master_sn: 3JKDH2T001KK23
